from exerciseEight import checkCostFunction
from exerciseEight import cofiCostFunc
from exerciseEight import estimateGaussian
from exerciseEight import loadMovieList
from exerciseEight import multivariateGaussian
from exerciseEight import normalizeRatings
from exerciseEight import selectThreshold
from exerciseEight import visualizeFit
